source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘8.0’

# ruby语法
# target数组 如果有新的target直接加入该数组
targetsArray = [‘MVPDemo’, ‘MVPDemoTests’, ‘MVPDemoUITests’]
# 循环
targetsArray.each do |t|
     target t do
        pod 'MJRefresh', '~> 3.1.12'
        pod 'Masonry', '~> 0.6.1'
        pod 'AFNetworking', '~> 3.1.0'
        pod 'XcodeCoverage', '~> 1.3.0'
        pod 'MJExtension'
        pod 'MBProgressHUD'
        pod 'SDWebImage'
        pod 'OCMock',      '~> 3.4'
        pod 'AMapLocation', '~>2.3.0'
    end
    
end

